server:
  port: 8090
  jwt:
    jwtSecretKey: 9EjDKJ8WQDABF0otRFUhD/wr0gBm+tjk/0k9ovYj7PZIAGGBM7SX3rs1klAL8ztNR
    algorithm: HS256
    issuer: issuer
    expiresIn: 15m

spring:
  application:
    name: assignment-sales-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/test?authSource=admin
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: assignment-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.value.default.type: com.challenge.entities.OrderEntity
      auto-offset-reset: earliest
      enable-auto-commit: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 6.0.2