server:
  port: ${SERVER_PORT}
  jwt:
    jwtSecretKey: ${JWT_SECRET}
    algorithm: HS256
    issuer: ${JWT_ISSUER}
    expiresIn: ${JWT_EXPIRATION}

spring:
  application:
    name: assignment-sales-service
  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}/${MONGO_DATABASE}?authSource=admin
  kafka:
    bootstrap-servers: ${KAFKA_HOST}
    consumer:
      group-id: assignment-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.value.default.type: com.challenge.entities.OrderEntity
      auto-offset-reset: earliest
      enable-auto-commit: true

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    listener:
      concurrency: 3 # Number of concurrent consumers

    template:
      default-topic: assignment-topic
  logging:
    level:
      org.springframework.kafka: DEBUG